# Generated by Django 6.0.1 on 2026-02-27

import re

from django.core.validators import RegexValidator
from django.db import migrations, models
from django.utils.text import slugify


def _seed_from_email(email):
    seed = (email or '').strip().lower()
    if '@' in seed:
        seed = seed.split('@', 1)[0]
    seed = slugify(seed).replace('-', '_')
    seed = re.sub(r'[^A-Za-z0-9_-]', '', seed)
    return (seed or 'user')[:40]


def _unique_username(User, base):
    candidate = base[:50]
    counter = 0
    while User.objects.filter(username__iexact=candidate).exists():
        counter += 1
        suffix = f'_{counter:02x}'
        candidate = f'{base[:50 - len(suffix)]}{suffix}'
    return candidate


def backfill_usernames(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    pending_users = User.objects.filter(models.Q(username__isnull=True) | models.Q(username=''))
    for user in pending_users.iterator():
        base = _seed_from_email(user.email)
        user.username = _unique_username(User, base)
        user.save(update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[
                    RegexValidator(
                        message='Username can only contain letters, numbers, hyphens, and underscores.',
                        regex='^[A-Za-z0-9_-]+$',
                    )
                ],
            ),
        ),
        migrations.RunPython(backfill_usernames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    RegexValidator(
                        message='Username can only contain letters, numbers, hyphens, and underscores.',
                        regex='^[A-Za-z0-9_-]+$',
                    )
                ],
            ),
        ),
    ]
