# Generated by Django 6.0.1 on 2026-02-27

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_username'),
    ]

    operations = [
        TrigramExtension(),
    ]
