# Generated by Django 6.0.1 on 2026-02-27 09:42

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_enable_pg_trgm_extension'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['username'], name='accounts_user_username_trgm_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_name'], name='accounts_user_full_name_trgm_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
