# Generated by Django 6.0.1 on 2026-02-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_trgm_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pricing',
            field=models.CharField(choices=[('core', 'Core'), ('individual', 'Individual'), ('team', 'Team'), ('enterprise', 'Enterprise')], default='core', max_length=20),
        ),
    ]
