# Generated by Django 6.0.1 on 2026-02-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_plan',
            field=models.CharField(choices=[('CORE', 'Core'), ('INDIVIDUAL', 'Individual'), ('TEAM', 'Team'), ('ENTERPRISE', 'Enterprise')], default='CORE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
