# Generated by Django 6.0.1 on 2026-03-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_current_plan_user_plan_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pricing',
        ),
    ]
