# Generated by Django 6.0.1 on 2026-02-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='canvas_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
