# Generated by Django 6.0.1 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvases", "0003_rename_canvas_data_to_canvas_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="canvas",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="private",
                max_length=20,
            ),
        ),
    ]
