# Generated by Django 6.0.1 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvases", "0006_canvascomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="canvas",
            name="archive_reason",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="canvas",
            name="archive_recover_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="canvas",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="canvas",
            index=models.Index(fields=["workspace", "archived_at"], name="systems_workspace_archived_idx"),
        ),
    ]
