# Generated by Django 6.0.1 on 2026-02-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
        ("notifications", "0002_invitation_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditNotificationState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("read_at", models.DateTimeField(auto_now=True)),
                (
                    "audit_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_states",
                        to="audit.auditlog",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_notification_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_notification_states",
                "unique_together": {("user", "audit_log")},
            },
        ),
        migrations.AddIndex(
            model_name="auditnotificationstate",
            index=models.Index(fields=["user", "read_at"], name="audit_notif_user_id_0386df_idx"),
        ),
        migrations.AddIndex(
            model_name="auditnotificationstate",
            index=models.Index(fields=["user", "audit_log"], name="audit_notif_user_id_8fd4f4_idx"),
        ),
    ]
