# Generated by Django 6.0.1 on 2026-02-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auditnotificationstate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditnotificationstate',
            new_name='audit_notif_user_id_0e7334_idx',
            old_name='audit_notif_user_id_0386df_idx',
        ),
        migrations.RenameIndex(
            model_name='auditnotificationstate',
            new_name='audit_notif_user_id_7cedaa_idx',
            old_name='audit_notif_user_id_8fd4f4_idx',
        ),
    ]
