# Generated by Django 6.0.1 on 2026-02-04 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canvases', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('commenter', 'Commenter')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='canvases.canvas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'canvas_permissions',
                'indexes': [models.Index(fields=['canvas', 'user'], name='canvas_perm_canvas__8463e4_idx')],
                'unique_together': {('canvas', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspace_members',
                'indexes': [models.Index(fields=['workspace', 'user'], name='workspace_m_workspa_7679d4_idx')],
                'unique_together': {('workspace', 'user')},
            },
        ),
    ]
