# Generated by Django 6.0.1 on 2026-02-04 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0001_initial'),
        ('permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='canvaspermission',
            name='canvas_perm_canvas__8463e4_idx',
        ),
        migrations.RenameField(
            model_name='canvaspermission',
            old_name='canvas',
            new_name='system',
        ),
        migrations.AlterUniqueTogether(
            name='canvaspermission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='canvaspermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='canvaspermission',
            unique_together={('system', 'user')},
        ),
        migrations.AddIndex(
            model_name='canvaspermission',
            index=models.Index(fields=['system', 'user'], name='system_perm_system__589455_idx'),
        ),
        migrations.AlterModelTable(
            name='canvaspermission',
            table='system_permissions',
        ),
    ]
