# Generated by Django 6.0.1 on 2026-02-17 13:30

from django.db import migrations, models


def set_workspace_owner_as_admin(apps, schema_editor):
    WorkspaceMember = apps.get_model('permissions', 'WorkspaceMember')
    Workspace = apps.get_model('workspaces', 'Workspace')

    owner_workspace_ids = Workspace.objects.values_list('id', 'owner_id')
    owner_pairs = {(workspace_id, owner_id) for workspace_id, owner_id in owner_workspace_ids}

    for membership in WorkspaceMember.objects.all():
        if (membership.workspace_id, membership.user_id) in owner_pairs:
            membership.role = 'ADMIN'
            membership.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_remove_canvaspermission_canvas_perm_canvas__8463e4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10),
        ),
        migrations.RunPython(set_workspace_owner_as_admin, migrations.RunPython.noop),
    ]
