# Generated by Django 6.0.1 on 2026-03-05

from django.db import migrations, models


def backfill_joined_at(apps, schema_editor):
    WorkspaceMember = apps.get_model("permissions", "WorkspaceMember")
    WorkspaceMember.objects.filter(joined_at__isnull=True).update(joined_at=models.F("added_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0004_workspacemember_is_starred"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacemember",
            name="joined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspacemember",
            name="left_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_joined_at, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="workspacemember",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="workspacemember",
            constraint=models.UniqueConstraint(
                condition=models.Q(left_at__isnull=True),
                fields=("workspace", "user"),
                name="uq_workspace_member_active_only",
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemember",
            index=models.Index(fields=["workspace", "left_at"], name="workspace_m_workspa_07c817_idx"),
        ),
        migrations.AddIndex(
            model_name="workspacemember",
            index=models.Index(fields=["workspace", "role", "left_at"], name="workspace_m_workspa_4bde2a_idx"),
        ),
        migrations.AddIndex(
            model_name="workspacemember",
            index=models.Index(fields=["workspace", "joined_at"], name="workspace_m_workspa_2a84d8_idx"),
        ),
    ]
