# Generated by Django 6.0.1 on 2026-02-21

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX CONCURRENTLY IF NOT EXISTS workspaces_public_search_vector_gin_idx
                ON workspaces
                USING GIN (
                    (
                        setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
                        setweight(to_tsvector('english', coalesce(description, '')), 'C')
                    )
                )
                WHERE visibility = 'public';
            """,
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS workspaces_public_search_vector_gin_idx;",
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX CONCURRENTLY IF NOT EXISTS workspaces_public_name_trgm_gin_idx
                ON workspaces
                USING GIN (name gin_trgm_ops)
                WHERE visibility = 'public';
            """,
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS workspaces_public_name_trgm_gin_idx;",
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX CONCURRENTLY IF NOT EXISTS workspaces_public_description_trgm_gin_idx
                ON workspaces
                USING GIN ((coalesce(description, '')) gin_trgm_ops)
                WHERE visibility = 'public';
            """,
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS workspaces_public_description_trgm_gin_idx;",
        ),
    ]
