# Generated by Django 6.0.1 on 2026-02-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspacestar'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workspacestar',
            new_name='workspace_s_user_id_ed377f_idx',
            old_name='workspace_s_user_id_833830_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacestar',
            new_name='workspace_s_workspa_22e812_idx',
            old_name='workspace_s_workspa_96cce4_idx',
        ),
    ]
