# Generated by Django 6.0.1 on 2026-03-04 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_rename_workspace_s_user_id_833830_idx_workspace_s_user_id_ed377f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='ai_credits_monthly',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='workspace',
            name='ai_credits_remaining',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='workspace',
            name='ai_credits_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EvaluationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_id', models.CharField(max_length=8)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('workspace_tier', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('rules_evaluated', models.IntegerField()),
                ('rules_passed', models.IntegerField()),
                ('credit_consumed', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_logs', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'evaluation_log',
                'indexes': [models.Index(fields=['workspace', '-evaluated_at'], name='evaluation__workspa_ae8746_idx'), models.Index(fields=['user', '-evaluated_at'], name='evaluation__user_id_c391cd_idx')],
            },
        ),
    ]
