# Generated by Django 6.0.1 on 2026-03-04 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_workspace_ai_credits_monthly_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_id', models.CharField(max_length=8)),
                ('workspace_tier', models.CharField(default='core', max_length=20)),
                ('canvas_state', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('results', models.JSONField(blank=True, default=list)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('credits_exhausted', models.BooleanField(default=False)),
                ('credits_remaining', models.IntegerField(blank=True, null=True)),
                ('gemini_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'evaluation_runs',
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='evaluation__workspa_1bd502_idx'), models.Index(fields=['workspace', 'status'], name='evaluation__workspa_9b8e60_idx'), models.Index(fields=['user', '-created_at'], name='evaluation__user_id_8244b8_idx')],
            },
        ),
    ]
