# Generated by Django 6.0.1 on 2026-03-05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0006_evaluationrun"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="ai_credits_overage_used_monthly",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workspace",
            name="ai_credits_purchased_pack_remaining",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workspace",
            name="archive_reason",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="workspace",
            name="archive_recover_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="overage_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="WorkspaceCreditConsumption",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MONTHLY_POOL", "Monthly Pool"),
                            ("PURCHASED_PACK", "Purchased Pack"),
                            ("OVERAGE", "Overage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credits_used", models.PositiveIntegerField(default=1)),
                ("consumed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_consumptions",
                        to="workspaces.evaluationrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_credit_consumptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_consumptions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_credit_consumptions",
                "indexes": [
                    models.Index(fields=["workspace", "-consumed_at"], name="workspace_c_workspa_15d3d8_idx"),
                    models.Index(fields=["workspace", "consumed_at"], name="workspace_c_workspa_087f39_idx"),
                    models.Index(fields=["workspace", "user", "-consumed_at"], name="workspace_c_workspa_98baf7_idx"),
                    models.Index(fields=["source", "-consumed_at"], name="workspace_c_source_550f76_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="evaluationrun",
            index=models.Index(fields=["workspace", "created_at"], name="evalrun_workspace_created_idx"),
        ),
    ]
