# Generated by Django 6.0.1 on 2026-02-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvases", "0002_canvas_description_alter_canvas_canvas_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="canvas",
            old_name="canvas_data",
            new_name="canvas_state",
        ),
        migrations.AlterField(
            model_name="canvas",
            name="canvas_state",
            field=models.JSONField(
                blank=True,
                default={
                    "nodes": [],
                    "edges": [],
                    "viewport": {"zoom": 1, "pan": {"x": 0, "y": 0}},
                },
            ),
        ),
    ]
