# Generated by Django 6.0.1 on 2026-02-20 18:52

import systems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0004_canvas_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='canvas_state',
            field=models.JSONField(blank=True, default=canvases.models.default_canvas_state),
        ),
    ]
