###############################################################################
# GitHub OAuth-to-OIDC shim (github-cognito-openid-wrapper).
#
# GitHub speaks OAuth2, not OIDC. This API Gateway plus five Lambdas expose the
# standard OIDC endpoints (authorize / token / userinfo / jwks / discovery) that
# Cognito's generic OIDC identity provider federates against.
#
# The source is vendored at services/github-oidc-shim and built with
# `make shim-build`. The previous deployment was adopted from a CloudFormation
# stack with its signing key baked into the bundle, so it could not be rebuilt
# and did not survive the account move. Here the keypair is generated by
# Terraform and injected as ordinary Lambda env, and the code is built from the
# repo, so the whole thing is reproducible.
###############################################################################

data "aws_region" "current" {}

locals {
  functions = {
    authorize        = { handler = "authorize.handler" }
    token            = { handler = "token.handler" }
    userinfo         = { handler = "userinfo.handler" }
    jwks             = { handler = "jwks.handler" }
    openid_discovery = { handler = "openIdConfiguration.handler" }
  }

  # One API Gateway -> Lambda invoke permission per (method, path).
  permissions = {
    authorize_get = { fn = "authorize", method = "GET", path = "/authorize" }
    token_get     = { fn = "token", method = "GET", path = "/token" }
    token_post    = { fn = "token", method = "POST", path = "/token" }
    userinfo_get  = { fn = "userinfo", method = "GET", path = "/userinfo" }
    userinfo_post = { fn = "userinfo", method = "POST", path = "/userinfo" }
    jwks_get      = { fn = "jwks", method = "GET", path = "/.well-known/jwks.json" }
    openid_get    = { fn = "openid_discovery", method = "GET", path = "/.well-known/openid-configuration" }
  }

  fn_env = {
    GITHUB_CLIENT_ID     = var.github_client_id
    GITHUB_CLIENT_SECRET = var.github_client_secret
    GITHUB_API_URL       = var.github_api_url
    GITHUB_LOGIN_URL     = var.github_login_url
    COGNITO_REDIRECT_URI = var.cognito_redirect_uri
    JWT_PRIVATE_KEY      = tls_private_key.signing.private_key_pem
    JWT_PUBLIC_KEY       = tls_private_key.signing.public_key_pem
  }
}

# --- Signing key --------------------------------------------------------------
# Rotating it invalidates outstanding id_tokens (1h TTL), so users mid-login
# would need to retry. `terraform taint` this resource to rotate deliberately.
#
# 2048 bits, not upstream's 4096: the keys travel as Lambda environment
# variables, and Lambda caps the whole environment at 4KB. A 4096-bit private
# key PEM alone is ~3.2KB and pushes the total to 4412 bytes, which Lambda
# rejects outright. 2048 is the standard size for RS256 JWT signing keys.
resource "tls_private_key" "signing" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

# --- Code ---------------------------------------------------------------------
data "archive_file" "bundle" {
  type        = "zip"
  source_dir  = var.dist_dir
  output_path = "${path.module}/.build/github-oidc-shim.zip"
}

# --- IAM ----------------------------------------------------------------------
data "aws_iam_policy_document" "assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "fn" {
  for_each           = local.functions
  name               = "${var.name_prefix}-${replace(each.key, "_", "-")}"
  assume_role_policy = data.aws_iam_policy_document.assume.json
  tags               = var.tags
}

resource "aws_iam_role_policy_attachment" "basic" {
  for_each   = local.functions
  role       = aws_iam_role.fn[each.key].name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# --- Lambdas ------------------------------------------------------------------
resource "aws_cloudwatch_log_group" "fn" {
  for_each          = local.functions
  name              = "/aws/lambda/${var.name_prefix}-${replace(each.key, "_", "-")}"
  retention_in_days = var.log_retention_days
  tags              = var.tags
}

resource "aws_lambda_function" "fn" {
  for_each = local.functions

  function_name = "${var.name_prefix}-${replace(each.key, "_", "-")}"
  role          = aws_iam_role.fn[each.key].arn
  runtime       = var.runtime
  handler       = each.value.handler
  architectures = ["x86_64"]
  memory_size   = 128
  timeout       = 15

  filename         = data.archive_file.bundle.output_path
  source_code_hash = data.archive_file.bundle.output_base64sha256

  environment {
    variables = local.fn_env
  }

  tags       = var.tags
  depends_on = [aws_cloudwatch_log_group.fn]
}

# --- REST API -----------------------------------------------------------------
resource "aws_api_gateway_rest_api" "this" {
  name = var.name_prefix

  endpoint_configuration {
    types = ["EDGE"]
  }

  body = jsonencode({
    openapi = "3.0.1"
    info    = { title = var.name_prefix, version = "1.0" }
    paths = {
      for p in [
        { path = "/authorize", methods = ["get"], fn = "authorize" },
        { path = "/token", methods = ["get", "post"], fn = "token" },
        { path = "/userinfo", methods = ["get", "post"], fn = "userinfo" },
        { path = "/.well-known/jwks.json", methods = ["get"], fn = "jwks" },
        { path = "/.well-known/openid-configuration", methods = ["get"], fn = "openid_discovery" },
        ] : p.path => {
        for m in p.methods : m => {
          "x-amazon-apigateway-integration" = {
            uri                 = "arn:aws:apigateway:${data.aws_region.current.name}:lambda:path/2015-03-31/functions/${aws_lambda_function.fn[p.fn].arn}/invocations"
            httpMethod          = "POST"
            type                = "aws_proxy"
            passthroughBehavior = "when_no_match"
          }
        }
      }
    }
  })
}

resource "aws_api_gateway_deployment" "this" {
  rest_api_id = aws_api_gateway_rest_api.this.id

  triggers = {
    redeployment = sha1(aws_api_gateway_rest_api.this.body)
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_api_gateway_stage" "this" {
  rest_api_id   = aws_api_gateway_rest_api.this.id
  deployment_id = aws_api_gateway_deployment.this.id
  stage_name    = var.stage_name
  tags          = var.tags
}

resource "aws_lambda_permission" "invoke" {
  for_each = local.permissions

  statement_id  = "AllowApiGateway-${each.key}"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.fn[each.value.fn].function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "${aws_api_gateway_rest_api.this.execution_arn}/*/${each.value.method}${each.value.path}"
}
