# Generated by Django 6.0.1 on 2026-03-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_webhookeventlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhookeventlog',
            new_name='pay_wh_event_type_idx',
            old_name='payment_webh_event_t_6f57ab_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookeventlog',
            new_name='pay_wh_status_idx',
            old_name='payment_webh_status_88ca78_idx',
        ),
    ]
