from core.pricing import (
    PLAN_INDIVIDUAL,
    PLAN_TEAM,
    PLAN_BASE_PRICES,
)


PLAN_PRICES = {
    PLAN_INDIVIDUAL: PLAN_BASE_PRICES[PLAN_INDIVIDUAL],
    PLAN_TEAM: PLAN_BASE_PRICES[PLAN_TEAM],
}
