# Generated by Django 5.2.5 on 2026-02-26 23:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces", "0003_workspacestar"),
        ("canvases", "0006_canvascomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("scope", models.CharField(choices=[("workspace", "Workspace"), ("system", "System")], default="workspace", max_length=20)),
                ("category", models.CharField(default="general", max_length=50)),
                ("action", models.CharField(max_length=120)),
                ("target_name", models.CharField(blank=True, max_length=255)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("message", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("success", "Success"), ("warning", "Warning"), ("error", "Error")], default="success", max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_logs", to=settings.AUTH_USER_MODEL)),
                ("system", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="audit_logs", to="canvases.canvas")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_logs", to="workspaces.workspace")),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["workspace", "scope", "created_at"], name="audit_logs_workspa_33938a_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["workspace", "system", "created_at"], name="audit_logs_workspa_a333a4_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["workspace", "status", "created_at"], name="audit_logs_workspa_2fac75_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["workspace", "category", "created_at"], name="audit_logs_workspa_8979ac_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["workspace", "actor", "created_at"], name="audit_logs_workspa_030462_idx"),
        ),
    ]
