# Generated by Django 6.0.1 on 2026-02-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_workspa_3b8d55_idx',
            old_name='audit_logs_workspa_33938a_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_workspa_554896_idx',
            old_name='audit_logs_workspa_a333a4_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_workspa_2038d3_idx',
            old_name='audit_logs_workspa_2fac75_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_workspa_d032bb_idx',
            old_name='audit_logs_workspa_8979ac_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_workspa_06dc21_idx',
            old_name='audit_logs_workspa_030462_idx',
        ),
    ]
