name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'worker/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::042843883108:role/structra-github-OIDC-Role
          aws-region: ap-south-2

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push API image
        env:
          ECR_REGISTRY: 042843883108.dkr.ecr.ap-south-2.amazonaws.com
        run: |
          docker build -t $ECR_REGISTRY/structra-api:latest -f backend/Dockerfile ./backend
          docker push $ECR_REGISTRY/structra-api:latest

      - name: Build and push Worker image
        env:
          ECR_REGISTRY: 042843883108.dkr.ecr.ap-south-2.amazonaws.com
        run: |
          docker build -t $ECR_REGISTRY/structra-worker:latest -f worker/Dockerfile .
          docker push $ECR_REGISTRY/structra-worker:latest

      - name: Deploy via SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "i-0c1e5f5a79ec3f2af" \
            --document-name "AWS-RunShellScript" \
            --parameters commands=["sudo -u ubuntu bash /home/ubuntu/deploy.sh"] \
            --query "Command.CommandId" \
            --output text)

          echo "Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id $COMMAND_ID \
            --instance-id i-0c1e5f5a79ec3f2af

          aws ssm get-command-invocation \
            --command-id $COMMAND_ID \
            --instance-id i-0c1e5f5a79ec3f2af
